repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: autopep8-wrapper
    - id: flake8
      args: ['--ignore=E501']
